In [23]:
import numpy as np

In [24]:
print(np.arange(10,30,5))

[10 15 20 25]


In [25]:
print(np.arange(0,2,0.3))

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [26]:
x = np.linspace(0,99,100)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [27]:
# arange와 linspace의 차이
# arange는 1.25 미만까지
print(0,1+0.25,0.25)
# 0부터 1까지 포함
print(np.linspace(0,1.5))

0 1.25 0.25
[0.         0.03061224 0.06122449 0.09183673 0.12244898 0.15306122
 0.18367347 0.21428571 0.24489796 0.2755102  0.30612245 0.33673469
 0.36734694 0.39795918 0.42857143 0.45918367 0.48979592 0.52040816
 0.55102041 0.58163265 0.6122449  0.64285714 0.67346939 0.70408163
 0.73469388 0.76530612 0.79591837 0.82653061 0.85714286 0.8877551
 0.91836735 0.94897959 0.97959184 1.01020408 1.04081633 1.07142857
 1.10204082 1.13265306 1.16326531 1.19387755 1.2244898  1.25510204
 1.28571429 1.31632653 1.34693878 1.37755102 1.40816327 1.43877551
 1.46938776 1.5       ]


In [28]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [29]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

c=a-b
print(c)

print(b**2)

print(10*a)

print(a < 35)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[200 300 400 500]
[ True  True False False]


In [30]:
A = np.array([[1,1],
             [0,1]])
B = np.array([[2,0],
             [3,4]])

print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [31]:
print(A*B)
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [32]:
 a = np.arange(8).reshape(2,4) ** 2
 print(a)

[[ 0  1  4  9]
 [16 25 36 49]]


In [33]:
print(a.sum())

140


In [34]:
print(a.min())

0


In [35]:
print(a.max())

49


In [36]:
print(a.argmax())

7


In [37]:
print(a.cumsum())

[  0   1   5  14  30  55  91 140]


In [38]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
print(b.sum(axis=0))

[12 15 18 21]


In [40]:
print(b.sum(axis=1))

[ 6 22 38]


In [41]:
B = np.array([1,4,9])
print(B)

[1 4 9]


In [42]:
print(np.sqrt(B))

[1. 2. 3.]


In [45]:
a = np.arange(10)**2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [46]:
print(a[2])

4


In [47]:
print(a[2:5])

[ 4  9 16]


In [48]:
print(a[::-1])

[81 64 49 36 25 16  9  4  1  0]


In [50]:
a = np.arange(8)**2
print(a)

[ 0  1  4  9 16 25 36 49]


In [51]:
i = np.array([1,1,3,5])
print(a[i])

[ 1  1  9 25]


In [53]:
j = np.array([[3,4],[2,5]])
print(a[j])

[[ 9 16]
 [ 4 25]]


In [54]:
 a = np.arange(12).reshape(3,4)
 print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [55]:
b = a > 4
print(b)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [56]:
print(a[b])
a[b].shape

[ 5  6  7  8  9 10 11]


(7,)

In [57]:
a[b]=0
print(a)

[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


In [59]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [60]:
print(a.ravel())
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [61]:
print(a.reshape(2,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [62]:
print(a.T)
print(a.T.shape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [63]:
a = np.array([1,2,3,4]).reshape(2,2)
print(a)

[[1 2]
 [3 4]]


In [64]:
b = np.array([5,6,7,8]).reshape(2,2)
print(b)

[[5 6]
 [7 8]]


In [66]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [67]:
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [68]:
a = np.arange(12).reshape(2,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [69]:
print(np.hsplit(a,3))

[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


In [70]:
print(np.hsplit(a,(3,4)))

[array([[0, 1, 2],
       [6, 7, 8]]), array([[3],
       [9]]), array([[ 4,  5],
       [10, 11]])]
